version: "3"

services:
  backend:
    build:
      context: ./calculator-be
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./calculator-fe
    ports:
      - "4200:4200"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
